"""add_variant_color_fields

Revision ID: 3f39fe9bb50c
Revises: bfc4bc9985eb
Create Date: 2026-02-27 00:07:44.892354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f39fe9bb50c'
down_revision: Union[str, Sequence[str], None] = 'bfc4bc9985eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_variants', sa.Column('color_name', sa.String(), nullable=True))
    op.add_column('bike_variants', sa.Column('color_hex', sa.String(), nullable=True))
    op.add_column('bike_variants', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike_variants', 'is_available')
    op.drop_column('bike_variants', 'color_hex')
    op.drop_column('bike_variants', 'color_name')
    # ### end Alembic commands ###
